### ISSUE TITLE
My New Issue - Open text

### ISSUE THREAD

**Issue by DougAGault** [DougAGault/sandbox#1]
### Issue
Trying to get a feel for what the issue system has to offer. 

**Obviously** it allows for markup. It's interesting that the keyboard shortcuts work for things like **bold** and _italic_. 

You can also attache files by just dragging and dropping them here.
![image](https://user-images.githubusercontent.com/8780695/45563304-8aa82e80-b812-11e8-8661-89ac6de3b438.png)

> This is a block quote

`for x in 1..30 LOOP
  NULL;
END LOOP;`

@shakeebr - I referenced you

**Comment by DougAGault** [comment]
> ### Issue
> Trying to get a feel for what the issue system has to offer.
> 
> **Obviously** it allows for markup. It's interesting that the keyboard shortcuts work for things like **bold** and _italic_.
> 
> You can also attache files by just dragging and dropping them here.
> ![image](https://user-images.githubusercontent.com/8780695/45563304-8aa82e80-b812-11e8-8661-89ac6de3b438.png)
> 
> > This is a block quote
> 
> `for x in 1..30 LOOP NULL; END LOOP;`
> 
> @shakeebr - I referenced you

This entry quoted the above entry.

**Comment by shakeebr** [comment]
Looks good. Closing.
